version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./src:/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development